[package]
name = "maria"
version = "0.1.0"
authors = ["dragfire <asem.devajit@gmail.com>"]
edition = "2018"
description = "A compiler that compiles code."

[[bin]]
name = "maria"
path = "src/bin/maria.rs"

[dependencies]
